### ISSUE TITLE
[documentation] Name not always supplied for nodes

### ISSUE THREAD

**Issue by pseudomonas** [dhimmel/obonet#11]
In the example in README.md
`id_to_name = {id_: data['name'] for id_, data in graph.nodes(data=True)}`
throws a KeyError if any node lacks a name (as some do for e.g. deprecated nodes)

`id_to_name = {id_: data['name'] if 'name' in data else "<MISSING>" for id_, data in graph.nodes(data=True)}` 

fixes this problem.

(or `else None` or whatever)

**Comment by dhimmel** [comment]
Thanks @pseudomonas for the report! How about changing `data['name']` to `data.get('name')`?

Would you like to make the pull request, since you were the one who spotted the issue? If not, I will.

**Comment by dhimmel** [comment]
> as some do for e.g. deprecated nodes

Out of curiosity, which ontology was this?

**Comment by pseudomonas** [comment]
This was the MONDO disease ontology, but I'm pretty sure I've seen this behaviour for other ontologies too.

**Comment by pseudomonas** [comment]
I'm happy to let you do the fixing stuff, I've forgotten how to make pull requests and can't be bothered to look it up again right now.

I have no strong feelings about whether the value for missing nodes should be None or a placeholder string, given that it's only rough example code.

**Comment by bacharacherif** [comment]
Thank you for information
