### ISSUE TITLE
Getting a subgraph from obo file

### ISSUE THREAD

**Issue by BSharmi** [dhimmel/obonet#19]
Hello,

Is it possible to get a subgraph based on a list of GO IDs from the graph created using go-basic.obo file?

Thank you!

**Comment by dhimmel** [comment]
This should be straightforward.

networkx has the ability to create a subgraph, see [networkx.Graph.subgraph](https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.subgraph.html).

Are the input GO IDs all connected, i.e. immediate neighbors?

**Comment by BSharmi** [comment]
Yes I am able to create the subgraph with a list of nodes (GO terms) but I think (and I could be wrong!) having isolated nodes is okay and I do not need to include a connected set of terms.

**Comment by BSharmi** [comment]
Hi there another question I had is if it is possible to get the annotations embedded in the graph (for e.g. GO:0003674 molecular function) instead of just the GO term as the node string. Or is this feature already available?

Thank you!

**Comment by dhimmel** [comment]
@BSharmi can you elaborate? Are you asking whether you can gene Gene Ontology Annotations (i.e. genes linked to GO terms)? Or are you asking whether you can retrieve the name for a GO term, like "molecular function" for `GO:0003674`?

**Comment by BSharmi** [comment]
I was asking for the latter. I tried to build a subgraph with my GO list where each node is a GO appended with the name for the term (the example you have mentioned) but I think the function can only work with GO terms and not the term names. That is why wondering if it is possible

**Comment by dhimmel** [comment]
> I can think of one solution is to form the subgraph with just the terms and then re-label nodes with the new strings.

That seems like a good approach.
