### ISSUE TITLE
Use of OWL files

### ISSUE THREAD

**Issue by YojanaGadiya** [dhimmel/obonet#23]
Hey, is there a way to load OWL files into the graph? If not, are you aware of any roundabout that can help covert this OWL file into OBO as certain ontologies in OBO Foundry have links to just OWL files and not corresponding OBO files such as [this ](http://www.obofoundry.org/ontology/aro.html)

**Comment by dhimmel** [comment]
Yes, I've made a newer library called [nxontology](https://github.com/related-sciences/nxontology) that uses Pronto to read OWL files. 

With nxontology, you should be able to do:

```
from nxontology.imports import from_file
url = "http://purl.obolibrary.org/obo/aro.owl"
nxo = from_file(url)
```

Do you want to give that a try?

One different between obonet and nxontology is that obonet parses multiple edge types into a MultiDiGraph. nxontology only will parse the is_a / subClassOf edgges into a DiGraph.

**Comment by YojanaGadiya** [comment]
First of all, thank you for the solution. I did stumble upon the Pronto package and used it directly, but there were still issues with certain files probably due to the OWL version I assume. This was the traceback I get when using ARO ontology with the above code:

```
Traceback (most recent call last):
  File "annotate_assay.py", line 262, in <module>
    main()
  File "annotate_assay.py", line 255, in main
    nlp_mapping(
  File "annotate_assay.py", line 151, in nlp_mapping
    onto_graph = from_file(obo_file_path)
  File "lib\site-packages\nxontology\imports.py", line 63, in from_file
    onto = Prontology(handle=handle)
  File "lib\site-packages\pronto\ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "lib\site-packages\pronto\parsers\rdfxml.py", line 113, in parse_from
    self._extract_object_property(prop, curies)
  File "lib\site-packages\pronto\parsers\rdfxml.py", line 490, in _extract_object_property
    rel = (
  File "lib\site-packages\pronto\utils\meta.py", line 96, in newfunc
    return func(*args, **kwargs)
  File "lib\site-packages\pronto\ontology.py", line 499, in create_relationship
    raise ValueError(f"identifier already in use: {id} ({self[id]})")
ValueError: identifier already in use: is_a (Relationship('is_a', name='is a'))
```

Do you think you could try and fix this issue or would you rather want it to be fixed from Pronto side?

Side Note: The `pip install nxontology` was not able to push the current version that is there on GitHub. You might want to push this version to PyPI

**Comment by YojanaGadiya** [comment]
@dhimmel I found out the obo files for the remaining ontologies. Apparently, they were not available on OBO Foundry directly but on the GitHub page of each of the ontologies. This solved the problem. Closing the issue now.

**Comment by dhimmel** [comment]
> The pip install nxontology was not able to push the current version that is there on GitHub. You might want to push this version to PyPI

Ah my bad, just released https://github.com/related-sciences/nxontology/releases/tag/v0.2.0. Should be on PyPI soon.

> there were still issues with certain files probably due to the OWL version I assume. This was the traceback I get when using ARO ontology with the above code:

Yeah, the ARO ontology probably violates some part of the OWL spec. Anyways tagging @althonos in case he's interested in the error parsing the ARO OWL. Perhaps one solution would be for pronto to be a bit more permissive in such cases by issuing warnings rather than errors (not sure if that's possible here).

**Comment by YojanaGadiya** [comment]
Oh no, thats okay. Found the obo file for that on their github repository [here](https://github.com/arpcard/aro/tree/master/src/ontology)

**Comment by althonos** [comment]
I'll have a look when I can, thanks @dhimmel . The OWL-XML is quite permissive right now (much more than the OBO one, because the mapping of OWL to OBO means some data is necessarily lost), so this looks more like a plain bug to me.
